name: "Changelog Notifier"
description: "Notifies you in Telegram when there is a new release"
inputs:
  prefixes:
    description: "Prefixes to search for"
    required: false
    default: |-
      feat
      fix
      docs
      style
      refactor
      perf
      test
      chore
  token:
    description: "Telegram bot token"
    required: true
  chat_id:
    description: "Telegram chat id"
    required: true
  project_name:
    description: "Project name"
    required: false
  commits:
    description: "Commits"
    required: false
  yougile_api_key:
    description: "YouGile API key"
    required: true
  influxdb_url:
    description: "InfluxDB URL (e.g., http://influxdb:8181). If not provided, metrics are skipped."
    required: false
  influxdb_bucket:
    description: "InfluxDB bucket name"
    required: false
    default: "default"
  environment:
    description: "Deployment environment (used as metric label)"
    required: false
    default: "production"
  github_token:
    description: "GitHub token for API access (calculating lead times). If not provided, defaults to GITHUB_TOKEN environment variable."
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
