{
 "title": "DORA",
 "tags": [
  "dora",
  "metrics"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "Datasource", "query": "influxdb" },
   {
    "name": "project",
    "label": "Project",
    "query": "SHOW TAG VALUES FROM deployment WITH KEY = \"project\""
   },
   { "name": "has_task", "label": "Has Task", "query": "yes,no" }
  ]
 },
 "panels": [
  {
   "title": "Deployment Frequency (Daily)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "SELECT SUM(\"count\") \nFROM \"deployment\" \nWHERE \"project\" =~ /^${project:regex}$/ \nAND \"has_task\" =~ /^${has_task:regex}$/ \nAND $timeFilter \nGROUP BY time(1d) fill(0)"
    }
   ]
  },
  {
   "title": "Lead Time (Median)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT MEDIAN(\"seconds\") \nFROM \"lead_time\" \nWHERE \"project\" =~ /^${project:regex}$/ \nAND \"has_task\" =~ /^${has_task:regex}$/ \nAND $timeFilter \nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "MTTR (Median)",
   "type": "stat",
   "description": "Mean Time To Recovery",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT MEDIAN(\"seconds\") \nFROM \"mttr\" \nWHERE \"project\" =~ /^${project:regex}$/ \nAND \"has_task\" =~ /^${has_task:regex}$/ \nAND $timeFilter \nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($failures / $total)*100", "type": "math" }
   ]
  },
  {
   "title": "Cycle Time (Median)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT MEDIAN(\"seconds\") \nFROM \"cycle_time\" \nWHERE \"project\" =~ /^${project:regex}$/ \nAND \"has_task\" =~ /^${has_task:regex}$/ \nAND $timeFilter \nGROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}